#!/bin/sh

# script/server: Launch the application and any extra required processes locally.

set -e

(

cd "$(dirname "$0")/.."

if command -v docker-compose >/dev/null 2>&1; then
  docker-compose up
else
    python main.py
fi

)
